<a href="https://colab.research.google.com/github/SarathMohanIITD/Basic-Pytorch/blob/main/study_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
 ## Random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3073, 0.5656, 0.2498, 0.9608],
        [0.9110, 0.0637, 0.4325, 0.3564],
        [0.9253, 0.4412, 0.2460, 0.3681]])

## Create a random tensor with similar shape to an image

In [ ]:
random_image_tensor = torch.rand(size = (3,224,224))
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [ ]:
zeros = torch.zeros(size=(3,4))

In [ ]:
ones = torch.ones(size=(3,4))

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensors

In [ ]:
one_to_ten=torch.arange(1,11)

In [ ]:
rnge = torch.arange(start=1,end=11,step =1)
rnge

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensor like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data types

### Note : Tensor datatypes is one of the 3 big errors you'll run into with Pytorch and deep Learning
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [ ]:
 float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype = None,
                                device = 'cpu', 
                                requires_grad=False)
 float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor= float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Tensor operations 


In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
# multiply tensor by 10
tensor - tensor*10

tensor([ -9, -18, -27])

In [ ]:
# Element wise matrix multiplication
tensor*tensor

tensor([1, 4, 9])

In [ ]:
#Matrix multiplication
torch.matmul(tensor,tensor)


tensor(14)

## Tensor aggregation

In [ ]:
#Create a tensor
x = torch.arange(0,100,10)
print(x,x.dtype)


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.int64


In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
ange(1.torch.mean(x)

SyntaxError: ignored

This shows data type error 

In [ ]:
torch.mean(x.type(torch.float32))

## Finding the positional min and max

In [ ]:
x.argmin() # Gives the index value

## Reshaping ,stacking ,squeezing and unsqueezing tensors

 Reshaping - reshapes an input tensor to a defined shape 
* View      - Reutrn a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Cobining multiple tensors on top of each other (vstack) or side by side(hstack)  https://pytorch.org/docs/stable/generated/torch.stack.html
* Unsqueeze - Add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimension permute (swapped) in a certain way


In [ ]:
x = torch.arange(1.,10.)
x,x.shape

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

# Change view
### Changing z changes x ( because a view of a tensor shares the same memory as the original input )

In [ ]:
z= x.view(1,9)
z, z.shape

In [ ]:
z[:,0]=5
z,x

In [ ]:
x_stacked = torch.stack([x,x,x,x])  # dim = 0 is default
x_stacked 

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked

## Squeeze and unsqueeze
Returns a tensor with all the dimensions of input of size 1 removed.

For example, if input is of shape: (A×1×B×C×1×D) then the out tensor will be of shape: (A×B×C×D)|

input (Tensor) – the input tensor.

dim (int, optional) – if given, the input will be squeezed only in this dimension

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()




In [ ]:
z = torch.squeeze(x)
z.size()

In [ ]:
y = torch.squeeze(x, dim =0)  # makes the dim unchanged
y.size()

In [ ]:
y = torch.squeeze(x, dim =1)
y.size()

### torch.unsqueeze() - adds a single dimension to a target tensor at a a specific dim

In [ ]:
z_unsq = z.unsqueeze(dim=0)
z_unsq.shape

In [ ]:
z_unsq = z.unsqueeze(dim=1)
z_unsq.shape

## torch.permute rearranges the dim of a target tensor in a specified order

Common in image data

## Note : Permute is just a different view, no new copy is created

In [ ]:
x = torch.randn(224, 224, 3)
x.size()

In [ ]:
x.shape

In [ ]:
# rearranging axis
x_perm = x.permute(2,0,1)
x_perm.shape

 ## Indexing 

In [ ]:
import torch

In [ ]:
x= torch.arange(1,10).reshape([1,3,3])
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
# Get all values of 0th dim and 1st dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#get index of 0 of 0th and 1st dim and all valuese of 2nd dim
x[0,1,1]

tensor(5)

In [ ]:
x[0,0,1].shape

torch.Size([])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[:,1,1].shape

torch.Size([1])

In [ ]:
# index on x to return 9
print(x[0][2][2])

# Index on x to return 3,6,9
print(x[:,:,2])
print(x[:,:,2].shape)

tensor(9)
tensor([[3, 6, 9]])
torch.Size([1, 3])


## Numpy array to tensor

In [ ]:
import torch
import numpy as np

array =np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
print(array.dtype, tensor.dtype)

# WARNING: When converting from numpy -> pytorch, pytorch reflects numpy's default datatype float64

float64 torch.float64


In [ ]:
# Tensot to  numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of random) -> Random seed

https://pytorch.org/docs/stable/notes/randomness.html

In [ ]:
import torch
# create 2 random tensors

random_A = torch.rand(3,4)
random_B = torch.rand(3,4)
print(random_A)
print(random_B)
print(random_A==random_B)

tensor([[0.9824, 0.7946, 0.4115, 0.4123],
        [0.6820, 0.8886, 0.5651, 0.6177],
        [0.2711, 0.4843, 0.1785, 0.2821]])
tensor([[0.4439, 0.1097, 0.6828, 0.2802],
        [0.3475, 0.5697, 0.5821, 0.2146],
        [0.8969, 0.5516, 0.6802, 0.0988]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
from torch.random import manual_seed
## Lets make the random numbers reproducable
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)  # Both tensors will be same

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTroch objects on GPU

https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/


In [1]:
! nvidia-smi

Wed Feb 22 06:45:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P0    32W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
torch.cuda.is_available()

True

In [11]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# count number of devices
torch.cuda.device_count()

1

In [8]:
# Putting tensors/models on the GPU

tensor = torch.tensor([1,2,3])
print(tensor.device)


cpu


In [12]:
# move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [13]:
tensor_on_gpu.numpy()

TypeError: ignored

In [15]:
## TO FIX GPUT THENSOR WITH NUMPY ISSUE , WE CAN FIRST SET IT TO CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])